/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_practiceopencv_TestActivity */

#ifndef _Included_com_example_practiceopencv_TestActivity
#define _Included_com_example_practiceopencv_TestActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_practiceopencv_TestActivity
 * Method:    convertRGBtoGray
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_example_practiceopencv_TestActivity_convertRGBtoGray
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_example_practiceopencv_TestActivity
 * Method:    convertGraytoBinary
 * Signature: (JJJJ)V
 */
JNIEXPORT void JNICALL Java_com_example_practiceopencv_TestActivity_convertGraytoBinary
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong);

/*
 * Class:     com_example_practiceopencv_TestActivity
 * Method:    staffHistogram
 * Signature: (JJJ)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_com_example_practiceopencv_TestActivity_staffHistogram
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     com_example_practiceopencv_TestActivity
 * Method:    staffMorphology
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_example_practiceopencv_TestActivity_staffMorphology
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_example_practiceopencv_TestActivity
 * Method:    templateHandCraft
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_example_practiceopencv_TestActivity_templateHandCraft
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     com_example_practiceopencv_TestActivity
 * Method:    noteExtaction
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_example_practiceopencv_TestActivity_noteExtaction
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_example_practiceopencv_TestActivity
 * Method:    noteLabeling
 * Signature: (JJ)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_com_example_practiceopencv_TestActivity_noteLabeling
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
