/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_practiceopencv_CreateFragment */

#ifndef _Included_com_example_practiceopencv_CreateFragment
#define _Included_com_example_practiceopencv_CreateFragment
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_practiceopencv_CreateFragment
 * Method:    preprocess1
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_example_practiceopencv_SheetFragment_preprocess1
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_example_practiceopencv_CreateFragment
 * Method:    preprocess2
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_example_practiceopencv_SheetFragment_preprocess2
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_example_practiceopencv_CreateFragment
 * Method:    preprocess3
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_com_example_practiceopencv_SheetFragment_preprocess3
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_example_practiceopencv_CreateFragment
 * Method:    preprocess4
 * Signature: (J[I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_example_practiceopencv_SheetFragment_preprocess4
  (JNIEnv *, jobject, jlong, jintArray);

/*
 * Class:     com_example_practiceopencv_CreateFragment
 * Method:    process
 * Signature: (J[I)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_com_example_practiceopencv_SheetFragment_process
  (JNIEnv *, jobject, jlong, jintArray);

#ifdef __cplusplus
}
#endif
#endif
