/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_practiceopencv_PracticeActivity */

#ifndef _Included_com_example_practiceopencv_PracticeActivity
#define _Included_com_example_practiceopencv_PracticeActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_practiceopencv_PracticeActivity
 * Method:    preprocess1
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_example_practiceopencv_PracticeActivity_preprocess1
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_example_practiceopencv_PracticeActivity
 * Method:    preprocess2
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_example_practiceopencv_PracticeActivity_preprocess2
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_example_practiceopencv_PracticeActivity
 * Method:    preprocess3
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_com_example_practiceopencv_PracticeActivity_preprocess3
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_example_practiceopencv_PracticeActivity
 * Method:    preprocess4
 * Signature: (J[I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_example_practiceopencv_PracticeActivity_preprocess4
  (JNIEnv *, jobject, jlong, jintArray);

/*
 * Class:     com_example_practiceopencv_PracticeActivity
 * Method:    process
 * Signature: (J[I)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_com_example_practiceopencv_PracticeActivity_process
  (JNIEnv *, jobject, jlong, jintArray);

#ifdef __cplusplus
}
#endif
#endif
